version: '3'

volumes:
  grafanavolume:
  influxdbvolume:

services:
  grafana:
    image: grafana/grafana:4.3.2
    ports:
      - '3000:3000'
    links:
      - influxdb
    volumes:
      - grafanavolume:/var/lib/grafana
  influxdb:
    image: influxdb:1.2.4-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdbvolume:/var/lib/influxdb
